version: 1.0.{build}
image: Visual Studio 2017

configuration:
  - Debug
  - Release

platform:
  - Win32
  - x64
  - MinGW

# see "Skip commits" at https://www.appveyor.com/docs/how-to/filtering-commits/#commit-files-github-and-bitbucket-only
skip_commits:
  files:
    - '*.md'
    - .gitignore
    - .editorconfig
    - 'azure-pipelines*.yml'
    - 'ci/azure-pipelines/template*.yml'

install:
- cmd: |
    pip install openpyxl --user
    C:\msys64\usr\bin\bash --login -c "pacman -S --noconfirm mingw-w64-x86_64-gtest"

build_script:
- cmd: |
    build-all.bat %PLATFORM% %CONFIGURATION%
    tests\build-and-test.bat %PLATFORM% %CONFIGURATION%
- ps: |
    $wc = New-Object 'System.Net.WebClient'
    $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path ".\tests\build\$($env:platform)\$($env:configuration)\tests1.exe-googletest-$($env:platform)-$($env:configuration).xml"))

artifacts:
  - path: 'sakura-*$(platform)-$(configuration)*.zip'
  - path: 'sakura-*$(platform)-$(configuration)*.zip.md5'
  - path: 'sha256.txt'
  - path: '.\tests\build\$(platform)\$(configuration)\tests1.exe-googletest-$(platform)-$(configuration).xml'