version: 1.0.{build}
image: Visual Studio 2017

configuration:
  - Release
  - Debug

platform:
  - MinGW

build_script:
- cmd: |
    build-all.bat %PLATFORM% %CONFIGURATION%

artifacts:
- path: 'sakura-*$(platform)-$(configuration)*.zip'
