version: 1.0.{build}
image: Visual Studio 2017

configuration:
  - Release
  - Debug

platform:
  - Win32
  - x64
  - MinGW

install:
- cmd: |
    pip install openpyxl --user
    pip install chardet --user
    msiexec /i externals\cppcheck\cppcheck-1.84-x64-Setup.msi /quiet /qn /norestart /log cppcheck-install.log
    externals\doxygen\doxygen-1.8.14-setup.exe /silent /suppressmsgboxes

build_script:
- cmd: |
    checkEncoding.bat
    build-all.bat %PLATFORM% %CONFIGURATION%
    tests\build-and-test.bat %PLATFORM% %CONFIGURATION%

after_build:
- cmd: set SAKURA_TEST=tests\build\%PLATFORM%\%CONFIGURATION%\tests1.exe

test:
  assemblies:
    only:
      - '%SAKURA_TEST%'

test_script:
- cmd: |
    "%SAKURA_TEST%" --gtest_list_tests
    "%SAKURA_TEST%" | tests\test_result_filter_tell_AppVeyor.bat

artifacts:
- path: 'sakura-*$(platform)-$(configuration)*.zip'
