@echo off
setlocal ENABLEDELAYEDEXPANSION

rem Parameters

set  Platform=%~1
set    Config=%~2
set    Target=%~3
set Platforms=Win32 x64 MinGW
set   Configs=Release Debug
set   Targets=all sakura sakura_test sakura_lang_en_US sakura_autogenerated_files
for %%X in (Platform Config Target) do (
	call :VerifyParameter "!%%X!" "!%%Xs!"^
	|| (call :PrintParameterHelp "%%X" "!%%X!" "!%%Xs!" & exit /B 1)
)
if "%Target%" == "all" (
	rem omits the others' dependencies and (problematic!) MakefileMake.
	set Target=sakura sakura_test sakura_lang_en_US
)

rem Constants

set SakuraHome=%~dp0
if not defined Build^
   set Build=%~dp0%Platform%\%Config%

rem Setup

if not exist "%Build%"^
   mkdir "%Build%"

echo Output files will be placed in "%Build%".

rem googletest is needed to build tests.
git submodule init
git submodule update

call :SETENV_%Platform% "%Platform%" "%Config%"^
 || exit /B 1

rem Generate & Build

cmake %CMAKE_GEN_OPT% -H"%SakuraHome:\=/%" -B"%Build%"^
 || exit /B 1

for %%T in (%Target%) do (
	cmake --build "!Build!" !CMAKE_BLD_OPT! --target %%T^
	|| exit /B 1
)

exit /B 0

rem ------------------------------------------------------
rem    sub-routines
rem ------------------------------------------------------

:VerifyParameter
	for %%X in (%~2) do (
		if "%%X" == "%~1" (
			exit /B 0
		)
	)
exit /B 1

:PrintParameterHelp
	echo Parameter "%~2" was given to specify %~1.
	echo Known valid %~1s are...%~3.
exit /B 0

:SETENV_Win32
:SETENV_x64
	set CMAKE_GEN_OPT=-G "Visual Studio 15 2017" -A "%~1"
	set CMAKE_BLD_OPT=--config "%~2"
exit /B 0

:SETENV_MinGW
	set CMAKE_GEN_OPT=-G "MinGW Makefiles" -D CMAKE_BUILD_TYPE="%~2"
	set CMAKE_BLD_OPT=
	set PATH=C:\msys64\mingw64\bin;%PATH:C:\Program Files\Git\usr\bin;=%
	rem PATH=C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH:C:\Program Files\Git\usr\bin;=%
exit /B 0
